name: Documentation

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'

      - name: Install dependencies
        run: |
          julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=".")); Pkg.instantiate()'

      - name: Build and deploy docs
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          julia --project=docs docs/make.jl
